### ISSUE TITLE
Exception while sending message

### ISSUE THREAD

**Issue by jooray** [AsamK/textsecure-cli#2]
When sending a message with ./bin/textsecure-cli -u +85XXXXXX send -m "this is a test" +4YYYYYYYYYY I get an InvalidKeyException error. The error kind of makes sense, because the cipher key in *getCipher()*:

```java
  private Cipher getCipher(int mode, SecretKeySpec key, IvParameterSpec iv) {
    try {
      Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
      cipher.init(mode, key, iv);
      return cipher;
...
```
  is 256-bits (32 bytes), but AES expects 128-bits.

  The exception:
```
Exception in thread "main" java.lang.AssertionError: java.security.InvalidKeyException: Illegal key size
	at org.whispersystems.libaxolotl.SessionCipher.getCipher(SessionCipher.java:454)
	at org.whispersystems.libaxolotl.SessionCipher.getCiphertext(SessionCipher.java:399)
	at org.whispersystems.libaxolotl.SessionCipher.encrypt(SessionCipher.java:111)
	at org.whispersystems.textsecure.api.crypto.TextSecureCipher.encrypt(TextSecureCipher.java:68)
	at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessage(TextSecureMessageSender.java:342)
	at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessages(TextSecureMessageSender.java:304)
	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:244)
	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:121)
	at cli.Main.main(Main.java:127)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.whispersystems.libaxolotl.SessionCipher.getCipher(SessionCipher.java:449)
	... 8 more
```

  I don't know if this is a bug with textsecure-cli, libtextsecure-java or some recent change that is not reflected in these. Where does this key come from? 

  I checked libtextsecure-java and it didn't change much lately. It seems that also upstream TextSecure uses AES, not AES-256.

**Comment by AsamK** [comment]
I haven't encountered that bug, sending messages works for me. I just updated the libtextsecure-java dependency to the current version, could you retry and check if the error persists?

**Comment by jooray** [comment]
It persists. I did the registration again just in case, so deleted configuration file, got fresh install from your github, built it again and ran again.

```
$ ./bin/textsecure-cli -u +85XXXXXXXXX register -v
$ ./bin/textsecure-cli -u +85XXXXXXXXX verify 111111
$ ./bin/textsecure-cli -u +85XXXXXXXXX send -m test +421910865222
Exception in thread "main" java.lang.AssertionError: java.security.InvalidKeyException: Illegal key size
  at org.whispersystems.libaxolotl.SessionCipher.getCipher(SessionCipher.java:454)
  at org.whispersystems.libaxolotl.SessionCipher.getCiphertext(SessionCipher.java:399)
  at org.whispersystems.libaxolotl.SessionCipher.encrypt(SessionCipher.java:111)
  at org.whispersystems.textsecure.api.crypto.TextSecureCipher.encrypt(TextSecureCipher.java:79)
  at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessage(TextSecureMessageSender.java:399)
  at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessages(TextSecureMessageSender.java:361)
  at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:299)
  at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:123)
  at cli.Main.main(Main.java:129)
Caused by: java.security.InvalidKeyException: Illegal key size
  at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
  at javax.crypto.Cipher.implInit(Cipher.java:805)
  at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
  at javax.crypto.Cipher.init(Cipher.java:1396)
  at javax.crypto.Cipher.init(Cipher.java:1327)
  at org.whispersystems.libaxolotl.SessionCipher.getCipher(SessionCipher.java:449)
  ... 8 more
```

Could it be that some users have longer keys? Could you try sending to my phone number if it's phone number related (don't worry, my number is public anyway, so it does not matter that it's posted here).

**Comment by jooray** [comment]
Thanks, I got the text, so it's not my number. I tried some others and even send message back to you. Nothing helped.

I try to find out if it's something with my JDK, so I installed fresh JDK on a Linux system and tried it there. 

Updated the source to latest master to be even with your development. Still happening.

Do you have any idea what could be different? Where does the particular key come from? Is it the server? I can debug, so we can maybe compare if the server returns a different key size for you.

**Comment by AsamK** [comment]
I just looked at the getCipher() in the debugger, the key size is also 32 bytes for me. I would guess it has something to do with your JDK. I'm using the openjdk 8.

**Comment by jooray** [comment]
OK, solved, thanks for helping me out! It really was JDK.

Maybe catching this exception and hinting people would be a good idea (pointing them to a wiki). 

For Oracle VM, you need to install "export jurisdiction policy file". Howto:

https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters

Same for Linux and OS X.
